server:
  port: 8000

spring:
  application:
    name: gulimall-member
  datasource:
    username: root
    password: 847144514
    url: jdbc:mysql://114.115.246.166/gulimall_ums?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.66.76:8848


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto