spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.66.76:8848
  thymeleaf:
    cache: false
  redis:
    host: www.srznet.top
    port: 6379
    password: 847144514
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m

