server:
  port: 88

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.246.166:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
            #http://localhost:88/?url=baidu

        - id: test_route2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
            #http://localhost:88/?url=qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),//$\{segment}
          #http://localhost:88/api/renren-fast/product/pmscategory/list/tree ==> http://localhost:10000/product/pmscategory/list/tree

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
          #/api
          #http://localhost:8080/api/captcha.jpg ==> http://localhost:8080/renren-fast/captcha.jpg
