server:
  port: 88

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.246.166:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
            #http://localhost:88/?url=baidu
        - id: test_route2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
            #http://localhost:88/?url=qq