spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.66.76:8848
  alicloud:
    sms:
      host: https://dfsns.market.alicloudapi.com
      path: /data/send_sms
      template-id: CST_ptdie100
      appcode: a5b28410bec249f682407905fad686e6
server:
  port: 30001


